import { createContext, useContext, useState } from "react";
import type { ReactNode } from "react";

export type Lang = "en" | "fr";

const LanguageContext = createContext<{
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
} | undefined>(undefined);

/* ── Translations ─────────────────────────────────────────────────────────── */
const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Sidebar nav
    "nav.overview":     "Overview",
    "nav.projects":     "Projects",
    "nav.staff":        "Staff",
    "nav.assignments":  "Assignments",
    "nav.timesheets":   "Timesheets",
    "nav.import":       "Import Excel",
    "nav.estimation":   "Estimation",
    "nav.teambuilder":  "Team Builder",
    "nav.clients":      "Clients",
    "nav.pace":         "Project Pace",
    "nav.signout":      "Sign out",

    // Header titles
    "page.overview":    "Overview",
    "page.projects":    "Projects",
    "page.staff":       "Staff",
    "page.assignments": "Assignments",
    "page.import":      "Import Excel",
    "page.estimation":  "Budget Estimation",
    "page.clients":     "Clients",
    "page.pace":        "Project Pace",

    // Overview
    "overview.total_projects":   "Total Projects",
    "overview.over_budget":      "Over Budget",
    "overview.total_staff":      "Total Staff",
    "overview.burnout_risk":     "Burnout Risk",
    "overview.active":           "active",
    "overview.projects":         "projects",
    "overview.people":           "people",
    "overview.flagged":          "flagged",
    "overview.top_projects":     "Top Projects by Pace Index",
    "overview.by_status":        "Projects by Status",
    "overview.recent_alerts":    "Recent Alerts",
    "overview.no_alerts":        "No alerts yet.",
    "overview.on_track":         "On Track",
    "overview.at_risk":          "At Risk",
    "overview.over":             "Over Budget",

    // Staff
    "staff.collaborators":       "Collaborators",
    "staff.managers":            "Managers",
    "staff.admins":              "Admins",
    "staff.workers":             "Workers",
    "staff.add":                 "Add Staff Member",
    "staff.search":              "Search by name...",
    "staff.no_found":            "No members found.",
    "staff.add_one":             "+ Add one now",
    "staff.support_staff":       "Support staff — not tracked in timesheets",
    "staff.total_hours":         "Total",
    "staff.this_month":          "this month",

    // Staff modal
    "staff.modal.add_title":     "Add Staff Member",
    "staff.modal.edit_title":    "Edit",
    "staff.modal.delete_title":  "Delete Staff Member",
    "staff.modal.delete_confirm":"Are you sure you want to delete",
    "staff.modal.delete_warn":   "This action cannot be undone.",
    "staff.modal.cancel":        "Cancel",
    "staff.modal.add_btn":       "Add Member",
    "staff.modal.save_btn":      "Save Changes",
    "staff.modal.delete_btn":    "Delete",
    "staff.modal.saving":        "Saving...",
    "staff.modal.name":          "Full Name *",
    "staff.modal.email":         "Email *",
    "staff.modal.password":      "Password *",
    "staff.modal.password_edit": "New Password (leave blank to keep current)",
    "staff.modal.role":          "Role",
    "staff.modal.level":         "Level",
    "staff.modal.academic":      "Academic Level",
    "staff.modal.academic_ph":   "e.g. Master's in Accounting",
    "staff.modal.specializations":"Job Title / Specializations",
    "staff.modal.spec_hint":     "(comma-separated)",
    "staff.modal.spec_ph":       "e.g. Femme de ménage, Gardien",
    "staff.modal.name_required":    "Name is required.",
    "staff.modal.email_pw_required":"Email and password are required for non-worker roles.",
    "staff.modal.error":            "An error occurred.",
    "staff.modal.gender":           "Gender",
    "staff.modal.civil_status":     "Civil Status",
    "staff.modal.dob":              "Date of Birth",
    "staff.modal.pob":              "Place of Birth",
    "staff.modal.children":         "N° of Children",
    "staff.modal.address":          "Address",
    "staff.modal.hire_date":        "Hire Date",
    "staff.modal.contract_type":    "Contract Type",
    "staff.modal.contract_end":     "Contract End Date",
    "staff.modal.exp_start":        "Start of Prof. Experience",
    "staff.modal.department":       "Department",
    "staff.modal.pos_category":     "Position Category",
    "staff.modal.cout_horaire":     "Hourly Rate (DT/h)",
    // Staff card
    "staff.card.contract":          "Contract",
    "staff.card.hired":             "Hired",
    "staff.card.category":          "Category",
    "staff.card.gender":            "Gender",
    "staff.card.dob":               "Born",
    "staff.card.pob":               "From",
    "staff.card.address":           "Address",
    "staff.card.civil":             "Status",
    "staff.card.children":          "children",
    "staff.card.exp":               "Exp. since",
    "staff.card.end":               "End date",
    "staff.card.more":              "Show more",
    "staff.card.less":              "Show less",
    "staff.card.profile":           "Profile",
    // Profile page
    "staff.profile.back":           "Back to Staff",
    "staff.profile.years_b2a":      "yrs at B2A",
    "staff.profile.workload":       "Current Workload",
    "staff.profile.current_month":  "This month",
    "staff.profile.total_logged":   "Total hours logged",
    // Staff form sections
    "staff.section.account":        "Account",
    "staff.section.personal":       "Personal Information",
    "staff.section.contract":       "Contract & Position",

    // Import
    "import.title":              "Import History",
    "import.drag":               "Drag & drop an Excel file",
    "import.drop":               "Drop your Excel file here",
    "import.browse":             "or click to browse — .xlsx / .xls only",
    "import.btn":                "Import File",
    "import.importing":          "Importing...",
    "import.file":               "File",
    "import.type":               "Type",
    "import.records":            "Records",
    "import.status":             "Status",
    "import.by":                 "Imported By",
    "import.date":               "Date",
    "import.no_imports":         "No imports yet.",
    "import.change":             "Click to change",

    // Estimation
    "est.title":                 "Budget Estimation",
    "est.subtitle":              "AI-powered project duration & cost prediction",
    "est.coming_soon":           "Phase 2 — Coming Soon",
    "est.parameters":            "Project Parameters",
    "est.project_type":          "Project Type",
    "est.sector":                "Client Sector",
    "est.team_size":             "Team Size",
    "est.people":                "people assigned",
    "est.staff_mix":             "Staff Mix",
    "est.complexity":            "Complexity",
    "est.deadline":              "Strict deadline?",
    "est.deadline_hint":         "Affects risk and buffer in estimates",
    "est.generate":              "Generate Estimate",
    "est.fill":                  "Fill in the parameters and click",
    "est.not_enough":            "Not enough data yet",
    "est.not_enough_desc":       "You need at least",
    "est.not_enough_desc2":      "completed projects to generate reliable estimates.",
    "est.completed":             "completed",
    "est.needed":                "needed",
    "est.unlock":                "Estimation unlocks at",
    "est.currently":             "currently at",
    "est.hours_estimate":        "Hours Estimate",
    "est.cost_estimate":         "Cost Estimate",
    "est.hours":                 "hours",
    "est.optimistic":            "Optimistic",
    "est.likely":                "Most likely",
    "est.pessimistic":           "Pessimistic",
    "est.similar":               "Based on",
    "est.similar2":              "similar past projects",
    "est.high_conf":             "High confidence",
    "est.med_conf":              "Medium confidence",
    "est.low_conf":              "Low confidence",
    "est.based_on":              "Based on avg cost/hr per staff level from past imports",
    "est.project":               "Project",
    "est.actual_hours":          "Actual Hours",
    "est.budget":                "Budget",
    "est.over_budget":           "Over budget",
    "est.on_track":              "On track",

    // Assignments
    "assign.coming_soon":        "Assignments — Coming Soon",
    "assign.desc":               "The assignment matrix will be available once projects and staff are loaded.",

    // Clients
    "clients.add":               "Add Client",
    "clients.import":            "Import Excel",
    "clients.import_title":      "Import Clients from Excel",
    "clients.import_drop":       "Click or drag & drop your Excel file here",
    "clients.import_hint":       ".xlsx / .xls files only",
    "clients.import_btn":        "Import",
    "clients.importing":         "Importing...",
    "clients.import_new":        "new clients added",
    "clients.import_updated":    "updated",
    "clients.import_skipped":    "skipped",
    "clients.import_errors":     "rows had errors",
    "clients.modal.close":           "Close",
    "clients.profile.btn":           "View Profile",
    "clients.profile.back":          "Back to Clients",
    "clients.profile.contact":       "Contact",
    "clients.profile.business":      "Business",
    "clients.profile.legal":         "Legal & Tax",
    "clients.profile.portals":       "Portals & Notes",
    "clients.profile.pays":          "Country",
    "clients.profile.etat":          "Status",
    "clients.profile.forme_juridique": "Legal Form",
    "clients.profile.tva_regime":    "VAT Regime",
    "clients.profile.tva_date":      "VAT Date",
    "clients.profile.date_cloture":  "Closing Date",
    "clients.profile.idgrp":         "Group ID (Teams)",
    "clients.profile.espace_client": "Client Portal",
    "clients.profile.espace_extranet": "Extranet Portal",
    "clients.profile.assigned_to":   "Assigned To",
    "clients.profile.section_main":  "General",
    "clients.profile.section_legal": "Legal & Tax",
    "clients.profile.section_portals": "Portals",
    "clients.search":            "Search by name...",
    "clients.no_found":          "No clients found.",
    "clients.add_one":           "+ Add one now",
    "clients.modal.add_title":   "Add Client",
    "clients.modal.edit_title":  "Edit Client",
    "clients.modal.delete_title":"Delete Client",
    "clients.modal.delete_confirm":"Are you sure you want to delete",
    "clients.modal.delete_warn": "This action cannot be undone.",
    "clients.modal.cancel":      "Cancel",
    "clients.modal.add_btn":     "Add Client",
    "clients.modal.save_btn":    "Save Changes",
    "clients.modal.delete_btn":  "Delete",
    "clients.modal.saving":      "Saving...",
    "clients.modal.deleting":    "Deleting...",
    "clients.modal.error":       "An error occurred.",
    "clients.modal.name":        "Company / Client Name",
    "clients.modal.name_ph":     "e.g. Cabinet Dupont",
    "clients.modal.name_required":"Name is required.",
    "clients.modal.sector":      "Sector",
    "clients.modal.sector_ph":   "Select a sector",
    "clients.modal.phone":       "Phone",
    "clients.modal.email":       "Email",
    "clients.modal.address":     "Address",
    "clients.modal.address_ph":  "e.g. 12 Rue de la République, Tunis",
    "clients.modal.notes":       "Notes",
    "clients.modal.notes_ph":    "Any additional information...",

    // Audit Logs
    "nav.audit":                 "Audit Logs",
    "nav.parse":                 "File Parser",

    // Parse page
    "parse.title":               "Timesheet File Parser",
    "parse.subtitle":            "Upload a raw multi-sheet timesheet workbook. The tool will split each sheet into its own cleaned file, then package them into a ZIP ready to import.",
    "parse.step1":               "Upload the raw Excel workbook",
    "parse.step2":               "Each sheet is split and cleaned automatically",
    "parse.step3":               "Download the ZIP and import each file",
    "parse.drop_prompt":         "Drop your Excel file here, or click to browse",
    "parse.drop_now":            "Drop it!",
    "parse.drop_hint":           ".xlsx files only",
    "parse.preview_error":       "Could not read the file. Make sure it is a valid .xlsx workbook.",
    "parse.process_error":       "Processing failed. Please try again.",
    "parse.sheets_found":        "{n} sheet(s) detected — one file will be generated per sheet",
    "parse.process_btn":         "Split & Clean",
    "parse.processing":          "Processing…",
    "parse.download_btn":        "Download ZIP ({n} files)",
    "parse.new_file":            "Parse another file",
    "page.audit":                "Audit Logs",
    "page.profile":              "My Profile",
    "audit.title":               "Audit Logs",
    "audit.subtitle":            "Complete activity trail for all system actions",
    "audit.total":               "Total Events",
    "audit.today":               "Today",
    "audit.logins":              "Logins",
    "audit.imports":             "Imports",
    "audit.search_ph":           "Search by user, action, description...",
    "audit.filter.action":       "All Actions",
    "audit.filter.resource":     "All Resources",
    "audit.filter.from":         "From",
    "audit.filter.to":           "To",
    "audit.export_csv":          "Export CSV",
    "audit.col.time":            "Time",
    "audit.col.user":            "User",
    "audit.col.action":          "Action",
    "audit.col.resource":        "Resource",
    "audit.col.description":     "Description",
    "audit.col.ip":              "IP",
    "audit.no_logs":             "No audit logs found.",
    "audit.changes":             "Changes",
    "audit.changes.field":       "Field",
    "audit.changes.old":         "Old value",
    "audit.changes.new":         "New value",
    "audit.changes.none":        "No field-level changes recorded.",

    // Common
    "common.loading":            "Loading...",
    "common.no_data":            "No data available.",
    "common.edit":               "Edit",
    "common.delete":             "Delete",
    "common.search":             "Search",

    // Notifications (Header)
    "notif.over_budget":         "Over Budget",
    "notif.timesheets_pending":  "timesheets pending",
    "notif.burnout_risk":        "Burnout Risk",
    "notif.at_risk":             "At Risk Project",
    "notif.mark_all_read":       "Mark all as read",
    "notif.none":                "No notifications",
    "notif.dismiss":             "Dismiss notification",

    // Overview page
    "overview.page_title":               "Overview",
    "overview.updated_at":               "Updated at",
    "overview.refreshing":               "Refreshing…",
    "overview.refresh":                  "Refresh",
    "overview.error_load":               "Unable to load dashboard data.",
    "overview.pace_checker":             "Project Pace Checker",
    "overview.pace_search_ph":           "Search a project by name or client…",
    "overview.on_track_badge":           "On Track",
    "overview.at_risk_badge":            "At Risk",
    "overview.over_budget_badge":        "Over Budget",
    "overview.col_margin":               "Margin",
    "overview.hours_vs_budget":          "Hours — Actual / Budget",
    "overview.cost_vs_budget":           "Budget — Actual Cost / Budget (TND)",
    "overview.kpi_overrun_clients":      "Over-budget clients",
    "overview.kpi_overrun_sub":          "exceeding budget",
    "overview.kpi_all_ok":               "All within limits",
    "overview.kpi_active_collabs":       "Active Collaborators",
    "overview.kpi_burnout_sub":          "at burnout risk",
    "overview.kpi_ytd_gain":             "YTD Gain (top 10 clients)",
    "overview.top10_rentable":           "Top 10 Most Profitable Projects",
    "overview.top10_dep":                "Top 10 Over-Budget Projects",
    "overview.col_rank":                 "Rank",
    "overview.col_supervisor":           "Supervisor",
    "overview.col_client_h_mo":          "Client H/mo",
    "overview.col_consumed_ytd":         "Consumed YTD",
    "overview.col_gain_ytd":             "YTD Gain",
    "overview.col_avg_pace":             "Avg Pace",
    "overview.col_overrun":              "Overrun",
    "overview.heures_collab_title":      "Hours logged by collaborator",
    "overview.col_collab":               "Collaborator",
    "overview.col_level":                "Level",
    "overview.col_dept":                 "Department",
    "overview.col_total_h":              "Total H",
    "overview.col_validated_h":          "Validated H",
    "overview.col_pending":              "Pending",
    "overview.col_rejected_h":           "Rejected",
    "overview.col_tx_valid":             "Validation %",
    "overview.rent_manager_title":       "Portfolio profitability by manager",
    "overview.ytd_gain_total":           "Total YTD Gain",
    "overview.clients_overrun":          "Overruns",
    "overview.overrun_rate":             "Overrun rate",
    "overview.no_data":                  "No data",
    "overview.timesheets_pending_title": "Timesheets awaiting validation",
    "overview.collabs_concerned":        "Affected collaborators",
    "overview.total_pending_entries":    "Total pending entries",
    "overview.col_periods":              "Periods",
    "overview.col_nb_periods":           "# Periods",
    "overview.col_pending_entries":      "Pending entries",
    "overview.col_priority":             "Priority",
    "overview.no_timesheets_pending":    "No pending timesheets",
    "overview.showing":                  "Showing",
    "overview.collapse":                 "Collapse",
    "overview.show_all":                 "Show all",
    "overview.timesheets_rejected_title":"Rejected timesheets",
    "overview.total_rejected":           "Total rejected",
    "overview.no_timesheets_rejected":   "No rejected timesheets",
    "overview.col_date":                 "Date",
    "overview.col_hours":                "Hours",
    "overview.col_project":              "Project",
    "overview.col_status":               "Status",
    "overview.rejected_badge":           "Rejected",
    "overview.annual_budget":            "Annual Budget",
    "overview.active_clients":           "Active Clients",
    "overview.ytd_consumed":             "YTD Consumed",
    "overview.ytd_client_gain":          "YTD Client Gain",
    "overview.this_month_hours":         "This Month Hours",
    "overview.pace_health":              "Pace Health",
    "overview.all_submitted":            "All submitted",
    "overview.pending_count":            "pending",

    // Assignments page
    "assign.title":              "Assignments",
    "assign.collabs_active":     "Collabs Active",
    "assign.total_hours":        "Total Hours",
    "assign.clients_served":     "Clients Served",
    "assign.search_ph":          "Search collaborator…",
    "assign.view_matrix":        "Matrix",
    "assign.view_workload":      "Workload",
    "assign.view_heatmap":       "Heatmap",
    "assign.view_collabs":       "Collabs",
    "assign.view_supervisors":   "Supervisors",
    "assign.no_data_period":     "No data for this period",
    "assign.no_ts_data":         "No timesheet data for this period",
    "assign.no_data_available":  "No data available",
    "assign.overloaded":         "overloaded",
    "assign.capacity":           "of 160h capacity",
    "assign.hours_by_client":    "Hours by client",
    "assign.daily_log":          "Daily log",
    "assign.col_client":         "Client",
    "assign.col_primary_sup":    "Primary Supervisor",
    "assign.col_secondary_sup":  "Secondary Supervisor",
    "assign.no_supervisor_data": "No supervisor data for this year",

    // Import page — maintenance section
    "import.maintenance_title":      "Data Maintenance",
    "import.cleanup_title":          "Cleanup Orphaned Data",
    "import.cleanup_desc":           "Remove timesheets, time entries, and affectations that belong to staff members who have already been deleted.",
    "import.timesheets_removed":     "timesheets removed",
    "import.time_entries_removed":   "time entries removed",
    "import.affectations_removed":   "affectations removed",
    "import.cleaning_up":            "Cleaning up...",
    "import.run_cleanup":            "Run Cleanup",
    "import.col_file":               "File",
    "import.col_type":               "Type",
    "import.col_records":            "Records",
    "import.col_status":             "Status",
    "import.col_by":                 "Imported By",
    "import.col_date":               "Date",
    "import.no_imports_yet":         "No imports yet.",
  },

  fr: {
    // Sidebar nav
    "nav.overview":     "Vue d'ensemble",
    "nav.projects":     "Projets",
    "nav.staff":        "Personnel",
    "nav.assignments":  "Affectations",
    "nav.timesheets":   "Fiches Horaires",
    "nav.import":       "Importer Excel",
    "nav.estimation":   "Estimation",
    "nav.teambuilder":  "Équipe",
    "nav.clients":      "Clients",
    "nav.pace":         "Rythme Projets",
    "nav.signout":      "Se déconnecter",

    // Header titles
    "page.overview":    "Vue d'ensemble",
    "page.projects":    "Projets",
    "page.staff":       "Personnel",
    "page.assignments": "Affectations",
    "page.import":      "Importer Excel",
    "page.estimation":  "Estimation Budgétaire",
    "page.clients":     "Clients",
    "page.pace":        "Rythme Projets",

    // Overview
    "overview.total_projects":   "Total Projets",
    "overview.over_budget":      "Hors Budget",
    "overview.total_staff":      "Total Personnel",
    "overview.burnout_risk":     "Risque Burnout",
    "overview.active":           "actifs",
    "overview.projects":         "projets",
    "overview.people":           "personnes",
    "overview.flagged":          "signalés",
    "overview.top_projects":     "Top Projets par Indice de Rythme",
    "overview.by_status":        "Projets par Statut",
    "overview.recent_alerts":    "Alertes Récentes",
    "overview.no_alerts":        "Aucune alerte pour l'instant.",
    "overview.on_track":         "Dans les délais",
    "overview.at_risk":          "À risque",
    "overview.over":             "Hors budget",

    // Staff
    "staff.collaborators":       "Collaborateurs",
    "staff.managers":            "Managers",
    "staff.admins":              "Admins",
    "staff.workers":             "Employés de service",
    "staff.add":                 "Ajouter un membre",
    "staff.search":              "Rechercher par nom...",
    "staff.no_found":            "Aucun membre trouvé.",
    "staff.add_one":             "+ Ajouter maintenant",
    "staff.support_staff":       "Personnel de service — non suivi dans les feuilles de temps",
    "staff.total_hours":         "Total",
    "staff.this_month":          "ce mois",

    // Staff modal
    "staff.modal.add_title":     "Ajouter un membre",
    "staff.modal.edit_title":    "Modifier",
    "staff.modal.delete_title":  "Supprimer un membre",
    "staff.modal.delete_confirm":"Êtes-vous sûr de vouloir supprimer",
    "staff.modal.delete_warn":   "Cette action est irréversible.",
    "staff.modal.cancel":        "Annuler",
    "staff.modal.add_btn":       "Ajouter",
    "staff.modal.save_btn":      "Enregistrer",
    "staff.modal.delete_btn":    "Supprimer",
    "staff.modal.saving":        "Enregistrement...",
    "staff.modal.name":          "Nom complet *",
    "staff.modal.email":         "Email *",
    "staff.modal.password":      "Mot de passe *",
    "staff.modal.password_edit": "Nouveau mot de passe (laisser vide pour conserver)",
    "staff.modal.role":          "Rôle",
    "staff.modal.level":         "Niveau",
    "staff.modal.academic":      "Niveau académique",
    "staff.modal.academic_ph":   "ex. Master en Comptabilité",
    "staff.modal.specializations":"Titre / Spécialisations",
    "staff.modal.spec_hint":     "(séparés par virgule)",
    "staff.modal.spec_ph":       "ex. Femme de ménage, Gardien",
    "staff.modal.name_required":    "Le nom est obligatoire.",
    "staff.modal.email_pw_required":"Email et mot de passe requis pour les rôles non-worker.",
    "staff.modal.error":            "Une erreur est survenue.",
    "staff.modal.gender":           "Genre",
    "staff.modal.civil_status":     "Situation familiale",
    "staff.modal.dob":              "Date de naissance",
    "staff.modal.pob":              "Lieu de naissance",
    "staff.modal.children":         "Nbre d'enfants",
    "staff.modal.address":          "Adresse",
    "staff.modal.hire_date":        "Date d'embauche",
    "staff.modal.contract_type":    "Type de contrat",
    "staff.modal.contract_end":     "Date de fin de contrat",
    "staff.modal.exp_start":        "Début d'exp. professionnelle",
    "staff.modal.department":       "Département",
    "staff.modal.pos_category":     "Catégorie de poste",
    "staff.modal.cout_horaire":     "Coût horaire (DT/h)",
    // Staff card
    "staff.card.contract":          "Contrat",
    "staff.card.hired":             "Embauché",
    "staff.card.category":          "Catégorie",
    "staff.card.gender":            "Genre",
    "staff.card.dob":               "Né(e) le",
    "staff.card.pob":               "Lieu",
    "staff.card.address":           "Adresse",
    "staff.card.civil":             "Situation",
    "staff.card.children":          "enfants",
    "staff.card.exp":               "Exp. depuis",
    "staff.card.end":               "Fin contrat",
    "staff.card.more":              "Voir plus",
    "staff.card.less":              "Voir moins",
    "staff.card.profile":           "Profil",
    // Profile page
    "staff.profile.back":           "Retour au personnel",
    "staff.profile.years_b2a":      "ans chez B2A",
    "staff.profile.workload":       "Charge actuelle",
    "staff.profile.current_month":  "Ce mois-ci",
    "staff.profile.total_logged":   "Total heures enregistrées",
    // Staff form sections
    "staff.section.account":        "Compte",
    "staff.section.personal":       "Informations personnelles",
    "staff.section.contract":       "Contrat & Poste",

    // Import
    "import.title":              "Historique des imports",
    "import.drag":               "Glissez-déposez un fichier Excel",
    "import.drop":               "Déposez votre fichier ici",
    "import.browse":             "ou cliquez pour parcourir — .xlsx / .xls uniquement",
    "import.btn":                "Importer le fichier",
    "import.importing":          "Importation...",
    "import.file":               "Fichier",
    "import.type":               "Type",
    "import.records":            "Enregistrements",
    "import.status":             "Statut",
    "import.by":                 "Importé par",
    "import.date":               "Date",
    "import.no_imports":         "Aucun import pour l'instant.",
    "import.change":             "Cliquer pour changer",

    // Estimation
    "est.title":                 "Estimation Budgétaire",
    "est.subtitle":              "Prédiction IA de la durée et du coût des projets",
    "est.coming_soon":           "Phase 2 — Bientôt disponible",
    "est.parameters":            "Paramètres du projet",
    "est.project_type":          "Type de projet",
    "est.sector":                "Secteur client",
    "est.team_size":             "Taille de l'équipe",
    "est.people":                "personnes assignées",
    "est.staff_mix":             "Composition de l'équipe",
    "est.complexity":            "Complexité",
    "est.deadline":              "Délai strict ?",
    "est.deadline_hint":         "Affecte le risque et les marges dans les estimations",
    "est.generate":              "Générer l'estimation",
    "est.fill":                  "Remplissez les paramètres et cliquez sur",
    "est.not_enough":            "Données insuffisantes",
    "est.not_enough_desc":       "Vous avez besoin d'au moins",
    "est.not_enough_desc2":      "projets terminés pour générer des estimations fiables.",
    "est.completed":             "terminés",
    "est.needed":                "requis",
    "est.unlock":                "L'estimation se débloque à",
    "est.currently":             "actuellement à",
    "est.hours_estimate":        "Estimation en heures",
    "est.cost_estimate":         "Estimation du coût",
    "est.hours":                 "heures",
    "est.optimistic":            "Optimiste",
    "est.likely":                "Le plus probable",
    "est.pessimistic":           "Pessimiste",
    "est.similar":               "Basé sur",
    "est.similar2":              "projets similaires passés",
    "est.high_conf":             "Haute confiance",
    "est.med_conf":              "Confiance moyenne",
    "est.low_conf":              "Faible confiance",
    "est.based_on":              "Basé sur le coût moyen/h par niveau depuis les imports",
    "est.project":               "Projet",
    "est.actual_hours":          "Heures réelles",
    "est.budget":                "Budget",
    "est.over_budget":           "Hors budget",
    "est.on_track":              "Dans les délais",

    // Assignments
    "assign.coming_soon":        "Affectations — Bientôt disponible",
    "assign.desc":               "La matrice d'affectation sera disponible une fois les projets et le personnel chargés.",

    // Clients
    "clients.add":               "Ajouter un client",
    "clients.import":            "Importer Excel",
    "clients.import_title":      "Importer des clients depuis Excel",
    "clients.import_drop":       "Cliquer ou glisser-déposer votre fichier Excel",
    "clients.import_hint":       "Fichiers .xlsx / .xls uniquement",
    "clients.import_btn":        "Importer",
    "clients.importing":         "Importation...",
    "clients.import_new":        "nouveaux clients ajoutés",
    "clients.import_updated":    "mis à jour",
    "clients.import_skipped":    "ignorés",
    "clients.import_errors":     "lignes avec erreurs",
    "clients.modal.close":           "Fermer",
    "clients.profile.btn":           "Voir le profil",
    "clients.profile.back":          "Retour aux clients",
    "clients.profile.contact":       "Contact",
    "clients.profile.business":      "Entreprise",
    "clients.profile.legal":         "Juridique & Fiscal",
    "clients.profile.portals":       "Portails & Notes",
    "clients.profile.pays":          "Pays",
    "clients.profile.etat":          "Statut",
    "clients.profile.forme_juridique": "Forme juridique",
    "clients.profile.tva_regime":    "Régime TVA",
    "clients.profile.tva_date":      "Date TVA",
    "clients.profile.date_cloture":  "Date de clôture",
    "clients.profile.idgrp":         "ID Groupe (Teams)",
    "clients.profile.espace_client": "Espace client",
    "clients.profile.espace_extranet": "Espace extranet",
    "clients.profile.assigned_to":   "Assigné à",
    "clients.profile.section_main":  "Général",
    "clients.profile.section_legal": "Juridique & Fiscal",
    "clients.profile.section_portals": "Portails",
    "clients.search":            "Rechercher par nom...",
    "clients.no_found":          "Aucun client trouvé.",
    "clients.add_one":           "+ Ajouter maintenant",
    "clients.modal.add_title":   "Ajouter un client",
    "clients.modal.edit_title":  "Modifier le client",
    "clients.modal.delete_title":"Supprimer le client",
    "clients.modal.delete_confirm":"Êtes-vous sûr de vouloir supprimer",
    "clients.modal.delete_warn": "Cette action est irréversible.",
    "clients.modal.cancel":      "Annuler",
    "clients.modal.add_btn":     "Ajouter",
    "clients.modal.save_btn":    "Enregistrer",
    "clients.modal.delete_btn":  "Supprimer",
    "clients.modal.saving":      "Enregistrement...",
    "clients.modal.deleting":    "Suppression...",
    "clients.modal.error":       "Une erreur est survenue.",
    "clients.modal.name":        "Nom de l'entreprise / client",
    "clients.modal.name_ph":     "ex. Cabinet Dupont",
    "clients.modal.name_required":"Le nom est obligatoire.",
    "clients.modal.sector":      "Secteur",
    "clients.modal.sector_ph":   "Sélectionner un secteur",
    "clients.modal.phone":       "Téléphone",
    "clients.modal.email":       "Email",
    "clients.modal.address":     "Adresse",
    "clients.modal.address_ph":  "ex. 12 Rue de la République, Tunis",
    "clients.modal.notes":       "Notes",
    "clients.modal.notes_ph":    "Informations complémentaires...",

    // Audit Logs
    "nav.audit":                 "Journal d'audit",
    "nav.parse":                 "Parseur de fichiers",

    // Parse page
    "parse.title":               "Parseur de fiches horaires",
    "parse.subtitle":            "Importez un classeur Excel multi-feuilles. L'outil sépare chaque feuille, nettoie les cellules fusionnées et génère un ZIP prêt à importer.",
    "parse.step1":               "Importez le classeur Excel brut",
    "parse.step2":               "Chaque feuille est séparée et nettoyée automatiquement",
    "parse.step3":               "Téléchargez le ZIP et importez chaque fichier",
    "parse.drop_prompt":         "Déposez votre fichier Excel ici, ou cliquez pour parcourir",
    "parse.drop_now":            "Déposez !",
    "parse.drop_hint":           "Fichiers .xlsx uniquement",
    "parse.preview_error":       "Impossible de lire le fichier. Vérifiez que c'est bien un classeur .xlsx valide.",
    "parse.process_error":       "Le traitement a échoué. Veuillez réessayer.",
    "parse.sheets_found":        "{n} feuille(s) détectée(s) — un fichier sera généré par feuille",
    "parse.process_btn":         "Séparer & Nettoyer",
    "parse.processing":          "Traitement en cours…",
    "parse.download_btn":        "Télécharger le ZIP ({n} fichiers)",
    "parse.new_file":            "Traiter un autre fichier",
    "page.audit":                "Journal d'audit",
    "page.profile":              "Mon profil",
    "audit.title":               "Journal d'audit",
    "audit.subtitle":            "Historique complet de toutes les actions système",
    "audit.total":               "Total événements",
    "audit.today":               "Aujourd'hui",
    "audit.logins":              "Connexions",
    "audit.imports":             "Imports",
    "audit.search_ph":           "Rechercher par utilisateur, action, description...",
    "audit.filter.action":       "Toutes les actions",
    "audit.filter.resource":     "Toutes les ressources",
    "audit.filter.from":         "Du",
    "audit.filter.to":           "Au",
    "audit.export_csv":          "Exporter CSV",
    "audit.col.time":            "Heure",
    "audit.col.user":            "Utilisateur",
    "audit.col.action":          "Action",
    "audit.col.resource":        "Ressource",
    "audit.col.description":     "Description",
    "audit.col.ip":              "IP",
    "audit.no_logs":             "Aucun journal d'audit trouvé.",
    "audit.changes":             "Modifications",
    "audit.changes.field":       "Champ",
    "audit.changes.old":         "Ancienne valeur",
    "audit.changes.new":         "Nouvelle valeur",
    "audit.changes.none":        "Aucune modification détaillée enregistrée.",

    // Common
    "common.loading":            "Chargement...",
    "common.no_data":            "Aucune donnée disponible.",
    "common.edit":               "Modifier",
    "common.delete":             "Supprimer",
    "common.search":             "Rechercher",

    // Notifications (Header)
    "notif.over_budget":         "Budget dépassé",
    "notif.timesheets_pending":  "timesheets en attente",
    "notif.burnout_risk":        "Risque burnout",
    "notif.at_risk":             "Projet à risque",
    "notif.mark_all_read":       "Tout marquer lu",
    "notif.none":                "Aucune notification",
    "notif.dismiss":             "Dismisser cette notification",

    // Overview page
    "overview.page_title":               "Vue d'ensemble",
    "overview.updated_at":               "Mis à jour à",
    "overview.refreshing":               "Actualisation…",
    "overview.refresh":                  "Actualiser",
    "overview.error_load":               "Impossible de charger les données du tableau de bord.",
    "overview.pace_checker":             "Vérificateur de rythme projet",
    "overview.pace_search_ph":           "Rechercher un projet par nom ou client…",
    "overview.on_track_badge":           "Dans les délais",
    "overview.at_risk_badge":            "À risque",
    "overview.over_budget_badge":        "Hors budget",
    "overview.col_margin":               "Marge",
    "overview.hours_vs_budget":          "Heures — Réel / Budget",
    "overview.cost_vs_budget":           "Budget — Coût Réel / Budget (TND)",
    "overview.kpi_overrun_clients":      "Clients en dépassement",
    "overview.kpi_overrun_sub":          "consomment plus que prévu",
    "overview.kpi_all_ok":               "Tous dans les limites",
    "overview.kpi_active_collabs":       "Collaborateurs actifs",
    "overview.kpi_burnout_sub":          "à risque burnout",
    "overview.kpi_ytd_gain":             "Gain YTD (top 10 clients)",
    "overview.top10_rentable":           "Top 10 Projets les plus rentables",
    "overview.top10_dep":                "Top 10 Projets en dépassement de budget",
    "overview.col_rank":                 "Rang",
    "overview.col_supervisor":           "Superviseur",
    "overview.col_client_h_mo":          "Client H/mois",
    "overview.col_consumed_ytd":         "Consommé YTD",
    "overview.col_gain_ytd":             "Gain YTD",
    "overview.col_avg_pace":             "Rythme moyen",
    "overview.col_overrun":              "Dépassement",
    "overview.heures_collab_title":      "Heures saisies par collaborateur",
    "overview.col_collab":               "Collaborateur",
    "overview.col_level":                "Niveau",
    "overview.col_dept":                 "Département",
    "overview.col_total_h":              "H Totales",
    "overview.col_validated_h":          "H Validées",
    "overview.col_pending":              "En attente",
    "overview.col_rejected_h":           "Rejetées",
    "overview.col_tx_valid":             "Tx Validation %",
    "overview.rent_manager_title":       "Rentabilité du portefeuille par manager",
    "overview.ytd_gain_total":           "Gain YTD total",
    "overview.clients_overrun":          "Dépassement",
    "overview.overrun_rate":             "Taux dep.",
    "overview.no_data":                  "Aucune donnée",
    "overview.timesheets_pending_title": "Timesheets en attente de validation",
    "overview.collabs_concerned":        "Collaborateurs concernés",
    "overview.total_pending_entries":    "Total entrées en attente",
    "overview.col_periods":              "Périodes",
    "overview.col_nb_periods":           "NB Périodes",
    "overview.col_pending_entries":      "Entrées en attente",
    "overview.col_priority":             "Priorité",
    "overview.no_timesheets_pending":    "Aucun timesheet en attente",
    "overview.showing":                  "Affichage de",
    "overview.collapse":                 "Réduire",
    "overview.show_all":                 "Tout afficher",
    "overview.timesheets_rejected_title":"Timesheets rejetés",
    "overview.total_rejected":           "Total rejetés",
    "overview.no_timesheets_rejected":   "Aucun timesheet rejeté",
    "overview.col_date":                 "Date",
    "overview.col_hours":                "Heures",
    "overview.col_project":              "Projet",
    "overview.col_status":               "Statut",
    "overview.rejected_badge":           "Rejeté",
    "overview.annual_budget":            "Budget Annuel",
    "overview.active_clients":           "Clients actifs",
    "overview.ytd_consumed":             "Consommé YTD",
    "overview.ytd_client_gain":          "Gain YTD clients",
    "overview.this_month_hours":         "Heures du mois",
    "overview.pace_health":              "Santé du rythme",
    "overview.all_submitted":            "Tout soumis",
    "overview.pending_count":            "en attente",

    // Assignments page
    "assign.title":              "Affectation",
    "assign.collabs_active":     "Collabs actifs",
    "assign.total_hours":        "Total Heures",
    "assign.clients_served":     "Clients servis",
    "assign.search_ph":          "Rechercher un collaborateur…",
    "assign.view_matrix":        "Matrice",
    "assign.view_workload":      "Charge",
    "assign.view_heatmap":       "Carte thermique",
    "assign.view_collabs":       "Collabs",
    "assign.view_supervisors":   "Superviseurs",
    "assign.no_data_period":     "Aucune donnée pour cette période",
    "assign.no_ts_data":         "Aucune feuille de temps pour cette période",
    "assign.no_data_available":  "Aucune donnée disponible",
    "assign.overloaded":         "surchargé",
    "assign.capacity":           "de capacité 160h",
    "assign.hours_by_client":    "Heures par client",
    "assign.daily_log":          "Journal journalier",
    "assign.col_client":         "Client",
    "assign.col_primary_sup":    "Superviseur principal",
    "assign.col_secondary_sup":  "Superviseur secondaire",
    "assign.no_supervisor_data": "Aucune donnée de supervision pour cette année",

    // Import page — maintenance section
    "import.maintenance_title":      "Maintenance des données",
    "import.cleanup_title":          "Nettoyer les données orphelines",
    "import.cleanup_desc":           "Supprimer les feuilles de temps, entrées de temps et affectations appartenant à des membres du personnel déjà supprimés.",
    "import.timesheets_removed":     "feuilles de temps supprimées",
    "import.time_entries_removed":   "entrées de temps supprimées",
    "import.affectations_removed":   "affectations supprimées",
    "import.cleaning_up":            "Nettoyage en cours...",
    "import.run_cleanup":            "Lancer le nettoyage",
    "import.col_file":               "Fichier",
    "import.col_type":               "Type",
    "import.col_records":            "Enregistrements",
    "import.col_status":             "Statut",
    "import.col_by":                 "Importé par",
    "import.col_date":               "Date",
    "import.no_imports_yet":         "Aucun import pour l'instant.",
  },
};

/* ── Provider ─────────────────────────────────────────────────────────────── */
export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Lang>(() =>
    (localStorage.getItem("lang") as Lang) || "fr"
  );

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("lang", l);
  };

  const t = (key: string): string =>
    translations[lang][key] ?? translations["en"][key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
  return ctx;
};
